// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "RcppArmadillo.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sigma2_update
double sigma2_update(int N, arma::vec y, arma::mat X, arma::uvec loc, arma::vec beta_old, arma::vec theta_old, double a_sigma2, double b_sigma2);
RcppExport SEXP _SpThreshold_sigma2_update(SEXP NSEXP, SEXP ySEXP, SEXP XSEXP, SEXP locSEXP, SEXP beta_oldSEXP, SEXP theta_oldSEXP, SEXP a_sigma2SEXP, SEXP b_sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type loc(locSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_old(beta_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_old(theta_oldSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma2(a_sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma2(b_sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(sigma2_update(N, y, X, loc, beta_old, theta_old, a_sigma2, b_sigma2));
    return rcpp_result_gen;
END_RCPP
}
// tau2_update
double tau2_update(int n, arma::vec theta, arma::mat Q, double a_tau2, double b_tau2);
RcppExport SEXP _SpThreshold_tau2_update(SEXP nSEXP, SEXP thetaSEXP, SEXP QSEXP, SEXP a_tau2SEXP, SEXP b_tau2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type a_tau2(a_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type b_tau2(b_tau2SEXP);
    rcpp_result_gen = Rcpp::wrap(tau2_update(n, theta, Q, a_tau2, b_tau2));
    return rcpp_result_gen;
END_RCPP
}
// beta_update
arma::vec beta_update(int N, int p, arma::vec y, arma::mat X, arma::uvec loc, arma::vec theta_old, double sigma2_old);
RcppExport SEXP _SpThreshold_beta_update(SEXP NSEXP, SEXP pSEXP, SEXP ySEXP, SEXP XSEXP, SEXP locSEXP, SEXP theta_oldSEXP, SEXP sigma2_oldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type loc(locSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_old(theta_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_old(sigma2_oldSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_update(N, p, y, X, loc, theta_old, sigma2_old));
    return rcpp_result_gen;
END_RCPP
}
// theta_update
arma::vec theta_update(int N, int n, arma::vec y, arma::mat X, arma::uvec loc, arma::vec m_vec, arma::vec beta_old, double sigma2_old, double tau2_old, arma::mat Q);
RcppExport SEXP _SpThreshold_theta_update(SEXP NSEXP, SEXP nSEXP, SEXP ySEXP, SEXP XSEXP, SEXP locSEXP, SEXP m_vecSEXP, SEXP beta_oldSEXP, SEXP sigma2_oldSEXP, SEXP tau2_oldSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type loc(locSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m_vec(m_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_old(beta_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_old(sigma2_oldSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_old(tau2_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(theta_update(N, n, y, X, loc, m_vec, beta_old, sigma2_old, tau2_old, Q));
    return rcpp_result_gen;
END_RCPP
}
// rho_update
Rcpp::List rho_update(int n, arma::mat W, arma::vec theta, double tau2, double rho_old, arma::mat Q_old, double Q_log_det_old, double proposal_sd, double a_rho, double b_rho);
RcppExport SEXP _SpThreshold_rho_update(SEXP nSEXP, SEXP WSEXP, SEXP thetaSEXP, SEXP tau2SEXP, SEXP rho_oldSEXP, SEXP Q_oldSEXP, SEXP Q_log_det_oldSEXP, SEXP proposal_sdSEXP, SEXP a_rhoSEXP, SEXP b_rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type rho_old(rho_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q_old(Q_oldSEXP);
    Rcpp::traits::input_parameter< double >::type Q_log_det_old(Q_log_det_oldSEXP);
    Rcpp::traits::input_parameter< double >::type proposal_sd(proposal_sdSEXP);
    Rcpp::traits::input_parameter< double >::type a_rho(a_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type b_rho(b_rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(rho_update(n, W, theta, tau2, rho_old, Q_old, Q_log_det_old, proposal_sd, a_rho, b_rho));
    return rcpp_result_gen;
END_RCPP
}
// SpThreshold
Rcpp::List SpThreshold(int mcmc_samples, arma::vec y, arma::mat X, arma::uvec loc, int model_indicator, Rcpp::Nullable<Rcpp::NumericMatrix> W, Rcpp::Nullable<double> proposal_sd_init, Rcpp::Nullable<double> a_sigma2_prior, Rcpp::Nullable<double> b_sigma2_prior, Rcpp::Nullable<double> a_tau2_prior, Rcpp::Nullable<double> b_tau2_prior, Rcpp::Nullable<double> a_rho_prior, Rcpp::Nullable<double> b_rho_prior, Rcpp::Nullable<Rcpp::NumericVector> beta_init, Rcpp::Nullable<Rcpp::NumericVector> theta_init, Rcpp::Nullable<double> sigma2_init, Rcpp::Nullable<double> tau2_init, Rcpp::Nullable<double> rho_init, int burnin, bool adapt_rho);
RcppExport SEXP _SpThreshold_SpThreshold(SEXP mcmc_samplesSEXP, SEXP ySEXP, SEXP XSEXP, SEXP locSEXP, SEXP model_indicatorSEXP, SEXP WSEXP, SEXP proposal_sd_initSEXP, SEXP a_sigma2_priorSEXP, SEXP b_sigma2_priorSEXP, SEXP a_tau2_priorSEXP, SEXP b_tau2_priorSEXP, SEXP a_rho_priorSEXP, SEXP b_rho_priorSEXP, SEXP beta_initSEXP, SEXP theta_initSEXP, SEXP sigma2_initSEXP, SEXP tau2_initSEXP, SEXP rho_initSEXP, SEXP burninSEXP, SEXP adapt_rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type mcmc_samples(mcmc_samplesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type loc(locSEXP);
    Rcpp::traits::input_parameter< int >::type model_indicator(model_indicatorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type W(WSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type proposal_sd_init(proposal_sd_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_prior(a_sigma2_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_prior(b_sigma2_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_tau2_prior(a_tau2_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_tau2_prior(b_tau2_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_rho_prior(a_rho_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_rho_prior(b_rho_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_init(sigma2_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type tau2_init(tau2_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type rho_init(rho_initSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< bool >::type adapt_rho(adapt_rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(SpThreshold(mcmc_samples, y, X, loc, model_indicator, W, proposal_sd_init, a_sigma2_prior, b_sigma2_prior, a_tau2_prior, b_tau2_prior, a_rho_prior, b_rho_prior, beta_init, theta_init, sigma2_init, tau2_init, rho_init, burnin, adapt_rho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpThreshold_sigma2_update", (DL_FUNC) &_SpThreshold_sigma2_update, 8},
    {"_SpThreshold_tau2_update", (DL_FUNC) &_SpThreshold_tau2_update, 5},
    {"_SpThreshold_beta_update", (DL_FUNC) &_SpThreshold_beta_update, 7},
    {"_SpThreshold_theta_update", (DL_FUNC) &_SpThreshold_theta_update, 10},
    {"_SpThreshold_rho_update", (DL_FUNC) &_SpThreshold_rho_update, 10},
    {"_SpThreshold_SpThreshold", (DL_FUNC) &_SpThreshold_SpThreshold, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpThreshold(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
