# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigma2_update <- function(N, y, X, loc, beta_old, theta_old, a_sigma2, b_sigma2) {
    .Call(`_SpThreshold_sigma2_update`, N, y, X, loc, beta_old, theta_old, a_sigma2, b_sigma2)
}

tau2_update <- function(n, theta, Q, a_tau2, b_tau2) {
    .Call(`_SpThreshold_tau2_update`, n, theta, Q, a_tau2, b_tau2)
}

beta_update <- function(N, p, y, X, loc, theta_old, sigma2_old) {
    .Call(`_SpThreshold_beta_update`, N, p, y, X, loc, theta_old, sigma2_old)
}

theta_update <- function(N, n, y, X, loc, m_vec, beta_old, sigma2_old, tau2_old, Q) {
    .Call(`_SpThreshold_theta_update`, N, n, y, X, loc, m_vec, beta_old, sigma2_old, tau2_old, Q)
}

rho_update <- function(n, W, theta, tau2, rho_old, Q_old, Q_log_det_old, proposal_sd, a_rho, b_rho) {
    .Call(`_SpThreshold_rho_update`, n, W, theta, tau2, rho_old, Q_old, Q_log_det_old, proposal_sd, a_rho, b_rho)
}

SpThreshold <- function(mcmc_samples, y, X, loc, model_indicator, W = NULL, proposal_sd_init = NULL, a_sigma2_prior = NULL, b_sigma2_prior = NULL, a_tau2_prior = NULL, b_tau2_prior = NULL, a_rho_prior = NULL, b_rho_prior = NULL, beta_init = NULL, theta_init = NULL, sigma2_init = NULL, tau2_init = NULL, rho_init = NULL, burnin = 0L, adapt_rho = TRUE) {
    .Call(`_SpThreshold_SpThreshold`, mcmc_samples, y, X, loc, model_indicator, W, proposal_sd_init, a_sigma2_prior, b_sigma2_prior, a_tau2_prior, b_tau2_prior, a_rho_prior, b_rho_prior, beta_init, theta_init, sigma2_init, tau2_init, rho_init, burnin, adapt_rho)
}
